
import pandas as pd

test = "MARESRESTTLDSHSAEDQMELLVIKVEQEESSPLAEETSWLGSPGPDRSRQRFRAFRYPEAAGPRQALSRLRELCRQWLRPDMHSKEQILELLVLEQFLTILPGELQAWVREQHPDSGEEVVALLEYLDRQLDDTPPQVPDDDDGQELLCSKAVLLTSAQGSESSQMEPVEPLLKQESLGSLPSEVRVTHVGHCGEDGVTATRLTSELQGLLKMEDVAPVLSPRWTEQDSSQMNLYKDGMQEHSGSLVSLDQDMQTKVRDLPRAEEYRDQKPEQTVCFLGEDTVPIPTGAEASEQEGKLQAAQKSATGTRRFYCRECGKSFAQSSGLSKHKRIHTGLKPYECEECGKAFIGSSALIIHQRVHTGEKPYECEECGKAFSHSSDLIKHQRTHTGEKPYECDDCGKTFTQSCSLLEHHRIHTGEKPYQCNMCPKAFRRSSHLLRHQRTHTGDKDFFVPEPYWESQSRVESHWENIETPVSYQCNDCERSFSRITSLIEHQKVHTGEKPFECQTCGKGFTRPSYLIQHQRRHTGKKTSVTVTPAVHSEVGVQLSLN"

Zkscan3_sequence_mouse = "MARESRESTTLDSHSAEDQMELLVIKVEQEESSPLAEETSWLGSPGPDRSRQRFRAFRYP\
EAAGPRQALSRLRELCRQWLRPDMHSKEQILELLVLEQFLTILPGELQAWVREQHPDSGE\
EVVALLEYLDRQLDDTPPQVPDDDDGQELLCSKAVLLTSAQGSESSQMEPVEPLLKQESL\
GSLPSEVRVTHVGHCGEDGVTATRLTSELQGLLKMEDVAPVLSPRWTEQDSSQMNLYKDG\
MQEHSGSLVSLDQDMQTKVRDLPRAEEYRDQKPEQTVCFLGEDTVPIPTGAEASEQEGKL\
QAAQKSATGTRRFYCRECGKSFAQSSGLSKHKRIHTGLKPYECEECGKAFIGSSALIIHQ\
RVHTGEKPYECEECGKAFSHSSDLIKHQRTHTGEKPYECDDCGKTFTQSCSLLEHHRIHT\
GEKPYQCNMCPKAFRRSSHLLRHQRTHTGDKDFFVPEPYWESQSRVESHWENIETPVSYQ\
CNDCERSFSRITSLIEHQKVHTGEKPFECQTCGKGFTRPSYLIQHQRRHTGKKTSVTVTP\
AVHSEVGVQLSLN"

Zkscan3_sequence_human = "MARELSESTALDAQSTEDQMELLVIKVEEEEAGFPSSPDLGSEGSRERFRGFRYPEAAGP\
REALSRLRELCRQWLQPEMHSKEQILELLVLEQFLTILPGNLQSWVREQHPESGEEVVVL\
LEYLERQLDEPAPQVSGVDQGQELLCCKMALLTPAPGSQSSQFQLMKALLKHESVGSQPL\
QDRVLQVPVLAHGGCCREDKVVASRLTPESQGLLKVEDVALTLTPEWTQQDSSQGNLCRD\
EKQENHGSLVSLGDEKQTKSRDLPPAEELPEKEHGKISCHLREDIAQIPTCAEAGEQEGR\
LQRKQKNATGGRRHICHECGKSFAQSSGLSKHRRIHTGEKPYECEECGKAFIGSSALVIH\
QRVHTGEKPYECEECGKAFSHSSDLIKHQRTHTGEKPYECDDCGKTFSQSCSLLEHHRIH\
TGEKPYQCSMCGKAFRRSSHLLRHQRIHTGDKNVQEPEQGEAWKSRMESQLENVETPMSY\
KCNECERSFTQNTGLIEHQKIHTGEKPYQCNACGKGFTRISYLVQHQRSHVGKNILSQ"

ZFs_mouse = [
"CRECGKSFAQSSGLSKHKRIH",\
"CEECGKAFIGSSALIIHQRVH",\
"CEECGKAFSHSSDLIKHQRTH",\
"CDDCGKTFTQSCSLLEHHRIH",\
"CNMCPKAFRRSSHLLRHQRTH",\
"CNDCERSFSRITSLIEHQKVH",\
"CQTCGKGFTRPSYLIQHQRRH"]

ZFs_human = ["CHECGKSFAQSSGLSKHRRIH",\
             "CEECGKAFIGSSALVIHQRVH",\
             "CEECGKAFSHSSDLIKHQRTH",\
             "CDDCGKTFSQSCSLLEHHRIH",\
             "CSMCGKAFRRSSHLLRHQRIH",\
             "CNECERSFTQNTGLIEHQKIH",\
             "CNACGKGFTRISYLVQHQRSH"]


ZFs = ZFs_human
Zkscan3_sequence = Zkscan3_sequence_human
ZFs = [ZF[4:-5] for ZF in ZFs]

print(ZFs)
print("\n")
ZFs_buffer_40 = []
for i in range(7):
    index = Zkscan3_sequence.find(ZFs[i])
    ZFs_buffer_40.append(Zkscan3_sequence[max(index-40, 0):min(index+12+40,len(Zkscan3_sequence))])

ZFs_df = pd.DataFrame({"label": [1.0]*7,'seq': ZFs_buffer_40, 'groups': [0]*7})

# data_set = pd.read_csv(data_set_file_path).dropna()
local_path = "/home/charles/Desktop/ZF_Binding/DeepZF-main"

ZFs_df.to_csv(local_path+"/Zkscan3_exps/"+f'Zkscan3_ZFs_df_{"human"}_for_binding_predictions.csv', sep=',', index=False)